### PR TITLE
Add Travis CI for compilation check

### PR DESCRIPTION
**Pull request by livibetter**
* Build on Linux and OS X with Clang and GCC.
* Install autoconf-archive-2017.03.21 (for `AX_IS_RELEASE(dash-version)`).
* Cache autoconf-archive for 1 day.

Here is the [build result](https://travis-ci.org/livibetter/Snakes/builds/343705885).

As we don't have tests (well, not sure how we can do that), this CI is only for the compilation and `make install`.  Invoking Snakes with `-h` (or `-v` soon) wouldn't mean much, nor would `{ sleep 0.1 ; yes ; } | ./snake` (with #14), it runs and that's all.

The caching actually slows down each build for about 10 to 20 seconds, but it won't be downloading autoconf-archive 4 times in every push.

I honestly don't know if we should cache or not, if @StefansM prefers not, I can remove the commit for caching.

### CODE REVIEW

**Comment by StefansM** [comment]
Looks good. I don't see a benefit to caching, as it should be faster to download the `.xz` from GNU than the uncompressed files from S3.

**Comment by livibetter** [comment]
The commit for caching is removed. ([build result](https://travis-ci.org/livibetter/Snakes/builds/344120788))

**Comment by StefansM** [comment]
Excellent -- nice work. Is there anything extra that needs to be configured to set this up?

**Comment by livibetter** [comment]
Not sure if it's same for repo in organization, but in personal account, I do like:

* Go to Settings
* Integration something?
* Add Service > Travis CI
* Click the link that leads to Travis CI's websites
* [Sync repos] > Tap on the switch to turn on

Once turned on, the CI will build on the next push.

**Comment by StefansM** [comment]
Okay, I've requested organisation access via the Travis CI website. For some reason, my account has been flagged as abusive (??? -- I only just signed up, and I just tried build a fork of pipes.c) so I will have to wait for support to get back to me.

**Comment by livibetter** [comment]
@StefansM That's weird.  I hope you get that sorted out soon and no harms done to your account.  But who flagged you?  GitHub or Travis CI?

And I've just received an email about Travis CI requests access to our **private** data, which link did you click on?  `travis-ci.org` or `.com` (for private repos)?  It should be the former.

I am holding off the request for approval because I don't want to grant the access to the private data, even we have none, if you did click on the wrong one, which I'd believe so, although I have no experience of turning on in a organization's repo.

**Comment by StefansM** [comment]
@livibetter Yes, very strange. It's Travis CI that flagged me. I hope to hear back from them soon, otherwise I guess I'm stuck.

I thought I used `.org`, but I could be mistaken. I regenerated the Travis CI auth token for my GitHub account and Travis CI didn't ask me for access to my private repos when I signed back in. Maybe you should reject the request and I can send another one.

**Comment by livibetter** [comment]
@StefansM done.

**Comment by StefansM** [comment]
OK, I've resent the request.

**Comment by livibetter** [comment]
I didn't receive another email, but it'd seem that access has to be granted.

[Travis CI](https://docs.travis-ci.com/user/github-oauth-scopes/) uses [`read:org`](https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/), so I've granted it.

**Comment by StefansM** [comment]
I heard back from Travis CI support in impressively quick time. Apparently they were making some changes to their infrastructure and mistakenly flagged my account. All fixed now and set up.

**Pull request merged**
