### PR TITLE
Rename project to "pipes.c" and bin to "pipes-c"

### PR DESCRIPTION
**Pull request by StefansM**
The new project name fits with the Pipeseroni convention, and the new binary name is unlikely to conflict with anything already installed.

Suggestions for the name of the binary are welcome. I don't want to include a dot, because it's very uncommon: `ls /usr/bin/*.*` gives less than 1/10 of the executables in that directory, and most of that is version numbering. Just `pipes` wins the autocomplete fight with the other projects in the org, and `pipesc` looks like it should be pronounced "pip esc".

Once we decide on a name, I'll tag the project as 1.0.0, closing #7.

### CODE REVIEW

**Comment by livibetter** [comment]
New project's name "pipes.c" is good, but I am not so sure about `pipes-c`, the dash is killing me, although I don't think there is a better name, perhaps `cpipes` like `cmatrix`?

Nonetheless, it's your call, as long as we don't conflict anything in the wild, any names is fine by me.

@Foggalong, any inputs?

**Comment by StefansM** [comment]
+1 for `cpipes`. "Coloured pipes" springs to mind, which is nice.

**Comment by livibetter** [comment]
"Coloured pipes," wish I had come up with that!
:rainbow: :cyclone: (there is no pipes emoji, and :snake: is crawling away, this is close enough)

**Comment by StefansM** [comment]
Nice. 1.0.0 incoming!

**Pull request merged**
